Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -23,16 +23,6 @@ jobs:
     - name: Checkout Repository
       uses: actions/checkout@v4
 
-    - name: Verify TestNG XML File Exists
-      run: |
-        ls -l $GITHUB_WORKSPACE
-        if [ -f "$GITHUB_WORKSPACE/headlesstestng.xml" ]; then
-          echo "TestNG XML file found!"
-        else
-          echo "TestNG XML file is missing!"
-          exit 1
-        fi
-
     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
@@ -40,12 +30,23 @@ jobs:
         distribution: 'temurin'
         cache: maven
 
-    - name: Run Tests with TestNG Suite
+    - name: Debug File Structure
+      run: find ${{ github.workspace }} -name "headlesstestng.xml"
+
+    - name: Verify headlesstestng.xml Exists
+      run: |
+        if [ -f "${{ github.workspace }}/headlesstestng.xml" ]; then
+          echo "headlesstestng.xml exists!"
+        else
+          echo "headlesstestng.xml is missing!"
+          exit 1
+        fi
+
+    - name: Run Tests with Maven
       run: mvn clean test -DsuiteXmlFile=headlesstestng.xml
 
     - name: Archive Test Reports
       uses: actions/upload-artifact@v4
       with:
-        name: TestReports
-        path: target/surefire-reports/*.xml
-
+        name: sparkHtml
+        path: reports/*.html
